# Generated by Django 3.1.5 on 2021-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('catagory', models.CharField(choices=[('Shows/Movies', 'Shows/Movies'), ('Books', 'Books'), ('Stationery', 'Stationery'), ('Clothing', 'Clothing'), ('Idea log', 'Idea log'), ('Health care', 'Health care'), ('Travel', 'Travel'), ('Errands', 'Errands'), ('Souvenirs', 'Souvenirs')], default='Errands', max_length=20)),
            ],
        ),
    ]
