# Generated by Django 3.1.5 on 2021-01-30 04:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel_1',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
