# Generated by Django 3.1.5 on 2021-04-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaperapp', '0002_auto_20210130_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel_1',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='newsmodel_1',
        ),
    ]
